from django.urls import path
from . import views
from . import planning_views

app_name = "operations"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("leads/", views.lead_list, name="leads"),
    path("leads/new/", views.quick_lead, name="quick_lead"),
    path("leads/<uuid:pk>/", views.lead_detail, name="lead_detail"),
    path("leads/<uuid:pk>/estimate/", views.estimate_create, name="estimate_create"),
    path("estimates/", views.estimate_list, name="estimates"),
    path("estimates/<uuid:pk>/", views.estimate_detail, name="estimate_detail"),
    path("estimates/<uuid:pk>/revise/", views.estimate_revise, name="estimate_revise"),
    path("estimates/<uuid:pk>/schedule/", views.book_job, name="book_job"),
    path("customers/", views.customer_list, name="customers"),
    path("customers/new/", views.customer_create, name="customer_create"),
    path("customers/<uuid:pk>/", views.customer_detail, name="customer_detail"),
    path("customers/<uuid:pk>/<str:kind>/new/", views.customer_related, name="customer_related"),
    path("schedule/", views.schedule, name="schedule"),
    path("schedule/block/", views.schedule_block, name="schedule_block"),
    path("schedule/block/<uuid:pk>/", planning_views.block_edit, name="block_edit"),
    path("schedule/block/<uuid:pk>/remove/", planning_views.block_remove, name="block_remove"),
    path("schedule/recurring/<uuid:pk>/", planning_views.plan_edit, name="plan_edit"),
    path("schedule/recurring/<uuid:pk>/generate/", planning_views.plan_generate, name="plan_generate"),
    path("deliveries/", planning_views.deliveries, name="deliveries"),
    path("deliveries/<uuid:pk>/retry/", planning_views.delivery_retry, name="delivery_retry"),
    path("jobs/", views.job_list, name="jobs"),
    path("jobs/<uuid:pk>/", views.job_detail, name="job_detail"),
    path("jobs/<uuid:pk>/reschedule/", views.job_reschedule, name="job_reschedule"),
    path("jobs/<uuid:pk>/cancel/", views.job_cancel, name="job_cancel"),
    path("jobs/<uuid:pk>/offer/", views.offer_create, name="offer_create"),
    path("jobs/<uuid:pk>/invoice/", views.invoice_create, name="invoice_create"),
    path("jobs/<uuid:pk>/recurring/", views.recurring_create, name="recurring_create"),
    path("offers/<uuid:pk>/", views.offer_detail, name="offer_detail"),
    path("offers/<uuid:pk>/withdraw/", views.offer_withdraw, name="offer_withdraw"),
    path("invoices/", views.invoice_list, name="invoices"),
    path("invoices/<uuid:pk>/", views.invoice_detail, name="invoice_detail"),
    path("compensation/", views.compensation, name="compensation"),
    path("notifications/", views.notifications, name="notifications"),
    path("price-book/", views.price_book, name="price_book"),
    path("price-book/new/", views.price_book_edit, name="price_book_create"),
    path("price-book/<uuid:pk>/", views.price_book_edit, name="price_book_edit"),
    path("reports/", views.reports, name="reports"),
    path("audit/", views.audit_log, name="audit"),
]
