# Generated by Django 5.2.17 on 2026-09-07 21:58

import django.db.models.deletion
import marketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('both', 'Both')], default='both', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(default=False, help_text='Only confirmed coverage appears publicly.')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('source_label', models.CharField(blank=True, max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('permission_to_publish', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('caption', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=250)),
                ('decorative', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=8)),
                ('original', models.FileField(blank=True, storage=marketing.models.PrivateMediaStorage(), upload_to=marketing.models.original_upload_path)),
                ('public_url', models.CharField(blank=True, editable=False, max_length=500)),
                ('variants', models.JSONField(blank=True, default=dict, editable=False)),
                ('poster', models.ImageField(blank=True, storage=marketing.models.PrivateMediaStorage(), upload_to=marketing.models.original_upload_path)),
                ('poster_url', models.CharField(blank=True, editable=False, max_length=500)),
                ('published_files', models.JSONField(blank=True, default=list, editable=False)),
                ('transcript', models.TextField(blank=True, help_text='Required for meaningful spoken video content.')),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=12)),
                ('visibility', models.CharField(choices=[('internal', 'Internal only'), ('customer', 'Customer visible'), ('public', 'Public marketing')], default='internal', max_length=12)),
                ('marketing_approved', models.BooleanField(default=False, help_text='Confirm owner/customer permission before publishing.')),
                ('consent_note', models.TextField(blank=True)),
                ('captured_at', models.DateField(blank=True, null=True)),
                ('location_label', models.CharField(blank=True, help_text='Neighborhood/city only; do not expose a private address.', max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.customer')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.job')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.property')),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('assets', models.ManyToManyField(blank=True, to='marketing.mediaasset')),
            ],
        ),
        migrations.CreateModel(
            name='BeforeAfterPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('published', models.BooleanField(default=False)),
                ('after', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='after_pairs', to='marketing.mediaasset')),
                ('before', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='before_pairs', to='marketing.mediaasset')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('summary', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marketing.mediaasset')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.service')),
            ],
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), models.Q(('marketing_approved', True), ('visibility', 'public')), _connector='OR'), name='published_media_requires_consent'),
        ),
    ]
